In [12]:
import torch

In [24]:
from darknet import parse_cfg 
from darknet import create_modules 

In [41]:
fpcg = parse_cfg('/home/ak/yolov3s/cfg/yolov3.cfg')

In [27]:
len(fpcg)

108

In [ ]:
fpcg

In [43]:
from darknet import create_modules


In [44]:
a,b = create_modules(fpcg)

In [ ]:
a

In [57]:
b[0][1].running_mean

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
for i,value in enumerate(fpcg):
    if fpcg[i]["type"] == "shortcut":
        print(fpcg[i])


NameError: name 'fpcg' is not defined

In [ ]:
blocks = parse_cfg("cfg/yolov3.cfg")


In [21]:
print(len(fpcg))

108


In [19]:
for i, module in enumerate(fpcg):
            module_type = module["type"]
            print(module_type)
            print(type(module["type"]))

net
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
convolutional
<class 'str'>
convolutional
<class 'str'>
shortcut
<class 'str'>
c

In [2]:
l = [1,2,3,4,5]
print(l[0:4])

[1, 2, 3, 4]


In [4]:
import torch
x= torch.arange(6)
print(x)

tensor([0, 1, 2, 3, 4, 5])


In [8]:
print(x.view(3,2))

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [9]:
y = torch.arange(6)

In [14]:
x=x.view(3,2)
y = y.view(3,2)

In [15]:
x_y = torch.cat((x,y),1)

In [16]:
print(x_y)

tensor([[0, 1, 0, 1],
        [2, 3, 2, 3],
        [4, 5, 4, 5]])


In [6]:
import cv2
import numpy as np
import torch

In [12]:

img = cv2.imread("dog-cycle-car.png")
img = cv2.resize(img, (416,416))          #Resize to the input dimension
   #Convert to float
    #img_ = Variable(img_)                     # Convert to Variable
    

In [20]:
print(img)

[[[ 57  61  61]
  [ 57  61  61]
  [ 57  61  61]
  ...
  [154 237 215]
  [ 84 144 137]
  [ 28  68  67]]

 [[ 57  61  61]
  [ 57  61  61]
  [ 57  61  61]
  ...
  [149 228 206]
  [ 70 126 120]
  [ 23  59  60]]

 [[ 57  61  61]
  [ 57  61  61]
  [ 57  61  61]
  ...
  [148 220 199]
  [ 53 104  98]
  [ 30  64  64]]

 ...

 [[182 169 160]
  [182 169 160]
  [181 168 159]
  ...
  [123 127 131]
  [ 93  96 100]
  [ 55  58  62]]

 [[182 169 160]
  [182 169 160]
  [181 168 159]
  ...
  [122 125 129]
  [ 82  85  89]
  [ 47  50  54]]

 [[181 168 159]
  [181 168 159]
  [181 168 159]
  ...
  [120 123 127]
  [ 74  78  82]
  [ 43  45  49]]]


In [21]:
img_ =  img[:,:,::-1].transpose((2,0,1))  # BGR -> RGB | H X W C -> C X H X W 
#img_ = img_[np.newaxis,:,:,:]/255.0       #Add a channel at 0 (for batch) | Normalise
#img_ = torch.from_numpy(img_).float()  

In [22]:
img_

array([[[ 61,  61,  61, ..., 215, 137,  67],
        [ 61,  61,  61, ..., 206, 120,  60],
        [ 61,  61,  61, ..., 199,  98,  64],
        ...,
        [160, 160, 159, ..., 131, 100,  62],
        [160, 160, 159, ..., 129,  89,  54],
        [159, 159, 159, ..., 127,  82,  49]],

       [[ 61,  61,  61, ..., 237, 144,  68],
        [ 61,  61,  61, ..., 228, 126,  59],
        [ 61,  61,  61, ..., 220, 104,  64],
        ...,
        [169, 169, 168, ..., 127,  96,  58],
        [169, 169, 168, ..., 125,  85,  50],
        [168, 168, 168, ..., 123,  78,  45]],

       [[ 57,  57,  57, ..., 154,  84,  28],
        [ 57,  57,  57, ..., 149,  70,  23],
        [ 57,  57,  57, ..., 148,  53,  30],
        ...,
        [182, 182, 181, ..., 123,  93,  55],
        [182, 182, 181, ..., 122,  82,  47],
        [181, 181, 181, ..., 120,  74,  43]]], dtype=uint8)

In [23]:
blocks

NameError: name 'blocks' is not defined

In [1]:
from util import load_classes

In [4]:
class_names = load_classes('/home/ak/yolov3s/data/coco.names')

In [7]:
len(class_names)

80